clusters:
### Enter your cluster configuration here
  - name:
    cluster_ip:
    ports:
      metrics: 9100
      api: 9101
      c_metrics: 9102
      c_advisor: 9103
    labels:
      env: lab
      region: east

### Make sure to enter your Hammerspace admin credentials here.
### These are used to query the cluster for node information.
### Example: username: admin, password: 1Hammerspace! 
hammerspace:
  username:
  password:

apps:
  grafana: true
  prometheus: true
  loki: true
  vector: true
  csi_driver: true
  nicegui: true

kubernetes:
  namespace: se-toolkit
  node_port_range: "30000-31000"

networking:
  expose_via_nodeport: true

global:
  prometheus:
    scrape_interval: 15s
    evaluation_interval: 15s
  namespace: hammerspace

