apiVersion: v1
kind: Service
metadata:
  name: mkdocs
  namespace: hammerspace
spec:
  type: NodePort
  selector:
    app: mkdocs
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32010

