apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: hammerspace
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
      name: web

