scrape_configs:
- job_name: prometheus
  static_configs:
  - labels:
      node_type: prometheus
  - targets:
    - localhost:9090
- job_name: cluster
  static_configs:
  - labels:
      cluster: forge.twocupsof.coffee
      instance: forge.twocupsof.coffee
      node_type: clusterip
    targets:
    - 192.168.100.200:9101
    - 192.168.100.200:9102
    - 192.168.100.200:9103
