global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
rule_files:
- /etc/prometheus/rules/*.rules
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: cluster
  static_configs:
  - targets:
    - 192.168.100.200:9101
    - 192.168.100.200:9102
    - 192.168.100.200:9103
    labels:
      cluster: forge.twocupsof.coffee
      instance: forge.twocupsof.coffee
      node_type: clusterip
