apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: hammerspace
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name            syslog
        Mode            udp
        Listen          0.0.0.0
        Port            32424
        Tag             hs.syslog.udp
        Parser          hammerspace_passthrough

    [INPUT]
        Name            syslog
        Mode            tcp
        Listen          0.0.0.0
        Port            32425
        Tag             hs.syslog.tcp
        Parser          hammerspace_passthrough

    [FILTER]
        Name                parser
        Match               *
        Key_Name            message
        Parser              hammerspace_structured
        Preserve_Key        True
        Reserve_Data        True

    [OUTPUT]
        Name              loki
        Match             *
        Host              loki.hammerspace.svc.cluster.local
        Port              3100
        Labels            job=hammerspace,event_type=$event_type,created_by=$created_by_name
        Line_Format       json
        Auto_Kubernetes_Labels Off

  parsers.conf: |-
    [PARSER]
    Name        hammerspace_passthrough
    Format      regex
    Regex       ^(?<message>.*)$
    Time_Keep   On

    [PARSER]
    Name        hammerspace_structured
    Format      regex
    Regex       ^<(?<pri>\d+)>.*?Hammerspace:\s+ClusterUUID=(?<cluster_uuid>[^\s]+)\s+Event\s+\[.*?type=(?<event_type>[A-Z_]+),.*?sourceName=(?<source_name>[^\s,]+),\s+severity=(?<severity>[A-Z]+),.*?createdById=Uoid\s+\[uuid=(?<created_by_id>[a-f0-9\-]+),\s*objectType=(?<created_by_type>[A-Z]+)\],\s+createdByName=(?<created_by_name>[^,]+),.*?\]\s+Description=(?<description>.+)
    Time_Keep   On

