apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit
  namespace: hammerspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
        - name: fluent-bit
          image: cr.fluentbit.io/fluent/fluent-bit:4.0.3
          ports:
            - containerPort: 32424
              name: syslog
          volumeMounts:
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
      volumes:
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config

